### ISSUE TITLE
Junkbot Font

### ISSUE THREAD

**Issue by tansiret** [1j01/janitorial-android#1]
First of all, amazing project! My childhood nostalgia, all open source.

I have found a free alternative to the Junkbot ingame font which resembles it %100 (https://www.ffonts.net/04b08.font?text=FACTORY). If you want, you can use it in the project.

Keep up the good work!

**Comment by 1j01** [comment]
Thank you!
You found it! I'd looked around for it a bit, but after trudging through one site's pixel fonts category, I decided to stop.
My sister will be pleased; she's a stickler for the font. :smile: 
I've added it to the game.
